/**
 * RazorShield AI — case file export.
 *
 * Builds a structured, analyst-facing JSON case file (transaction, customer
 * intelligence, AI conclusion, audit trail, analyst decision) and downloads
 * it as a client-side Blob. No backend involved — the same shape maps to a
 * future `GET /investigations/:id/export` endpoint.
 */

import { formatINR } from "@/lib/format";
import { ANALYSTS } from "@/data/mockData";
import type { CaseNote } from "@/store/appStore";
import type { Customer, Investigation, RiskAction, Transaction } from "@/types";

export interface CaseFile {
  document: string;
  version: string;
  exportedAt: string;
  exportedBy: string;
  transaction: Transaction;
  customer: Customer | null;
  ai: {
    summary: string | null;
    recommendation: string | null;
    confidence: number | null;
    evidenceUsed: string[];
    reasoning: string | null;
  };
  decision: {
    action: string;
    note?: string;
    at: string;
    by?: string;
  } | null;
  notebook: CaseNote[];
  provenance: {
    dataSource: string;
    disclaimer: string;
  };
}

export function buildCaseFile(
  txn: Transaction,
  investigation: Investigation | null,
  customer: Customer | null,
  notes: CaseNote[] = [],
  signedInAnalystId = "RK",
): CaseFile {
  const signedIn = ANALYSTS.find((a) => a.id === signedInAnalystId);
  const decision = investigation?.analystAction
    ? {
        action: investigation.analystAction,
        note: investigation.analystNote,
        at: investigation.resolvedAt ?? new Date().toISOString(),
        by: ANALYSTS.find((a) => a.id === signedInAnalystId)?.name,
      }
    : null;

  return {
    document: "RazorShield AI case file",
    version: "1.1",
    exportedAt: new Date().toISOString(),
    exportedBy: signedIn ? `${signedIn.name} · ${signedIn.level} analyst` : "analyst",
    transaction: {
      ...txn,
      investigation: investigation ?? txn.investigation,
    },
    customer,
    ai: {
      summary: txn.aiSummary,
      recommendation: txn.recommendation,
      confidence: txn.confidence,
      evidenceUsed: investigation?.evidenceUsed ?? [],
      reasoning: investigation?.reasoning ?? null,
    },
    decision,
    notebook: notes,
    provenance: {
      dataSource: "Demo environment — synthetic data only",
      disclaimer:
        "Generated by RazorShield AI for the Razorpay AI Buildathon 2026 demo. Scores and evidence are mock values produced by the deterministic demo engine.",
    },
  };
}

/** One-line human-readable header used in toasts / audit notes. */
export function caseFileHeadline(caseFile: CaseFile): string {
  const t = caseFile.transaction;
  return `${t.id} · ${formatINR(t.amount)} · ${t.riskScore}/100 · ${caseFile.decision?.action ?? "open"}`;
}

export function downloadCaseFile(caseFile: CaseFile): boolean {
  try {
    const blob = new Blob([JSON.stringify(caseFile, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${caseFile.transaction.id}-case-file.json`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 2000);
    return true;
  } catch {
    return false;
  }
}

/* ------------------------------------------------------------------ */
/* Audit export — resolved cases as CSV                                */
/* ------------------------------------------------------------------ */

function csvCell(value: string | number | null | undefined): string {
  const s = value == null ? "" : String(value);
  // escape quotes, wrap when the cell contains separators/newlines/quotes
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export const CASES_CSV_COLUMNS = [
  "case_id",
  "customer_id",
  "customer_name",
  "amount_inr",
  "risk_score",
  "risk_level",
  "signals",
  "ai_recommendation",
  "model_confidence_pct",
  "analyst_action",
  "resolved_by",
  "analyst_note",
  "notebook_entries",
  "opened_at",
  "resolved_at",
] as const;

/**
 * Build an audit-ready CSV of resolved cases (one row per analyst decision).
 * Mirrors the future `GET /investigations/export?format=csv` payload.
 */
export function buildCasesCsv(
  transactions: Transaction[],
  decisions: Record<string, { action: RiskAction; note?: string; at: string; analystId?: string }>,
  caseNotes: Record<string, CaseNote[]> = {},
): string {
  const rows = transactions
    .filter((t) => decisions[t.id])
    .map((t) => {
      const d = decisions[t.id];
      const resolvedBy = d.analystId ? ANALYSTS.find((a) => a.id === d.analystId)?.name ?? "" : "";
      return [
        t.id,
        t.customerId,
        t.customerName,
        t.amount,
        t.riskScore,
        t.riskLevel,
        t.signals.map((s) => s.type).join("|"),
        t.recommendation ?? "",
        t.confidence ?? "",
        d.action,
        resolvedBy,
        d.note ?? "",
        caseNotes[t.id]?.length ?? 0,
        t.timestamp,
        d.at,
      ].map(csvCell).join(",");
    });

  return [
    CASES_CSV_COLUMNS.join(","),
    ...rows,
    "",
    csvCell("RazorShield AI audit export — demo environment, synthetic data only"),
    csvCell(`Exported ${new Date().toISOString()} · ${rows.length} resolved case(s)`),
  ].join("\n");
}

export function downloadCasesCsv(
  transactions: Transaction[],
  decisions: Record<string, { action: RiskAction; note?: string; at: string; analystId?: string }>,
  caseNotes: Record<string, CaseNote[]> = {},
): boolean {
  try {
    const csv = buildCasesCsv(transactions, decisions, caseNotes);
    const stamp = new Date().toISOString().slice(0, 10);
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `razorshield-audit-${stamp}.csv`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 2000);
    return true;
  } catch {
    return false;
  }
}
